### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by AIManifest** [styler00dollar/VSGAN-tensorrt-docker#15]
Hi! This is amazing technology! I’m blown away. I’d love to contact you directly on how to use it in colab, I’m quite confused with the process. I’ve tried running it but not sure I’m running it correctly. Thanks in advance!

**Comment by styler00dollar** [comment]
Instructions are written. I admit thats it is not very noob friendly, but I wrote a lot. My focus is rather on performance and flexibility. If you have more spefic questions I can answer them. Maybe it is good to resolve it here so others can also see the solution, but don't use github like a discord chat.

**Comment by AIManifest** [comment]
Thank you for your response! And yes while I’m very much a noob, I’m also more of a visual/hands on learner. My question would be, for the colab version, do we need to run all the cells before the ‘inference.py’? I skipped the tensor RT cells because it says to, but should I run it anyway? And how would we inference a folder of frames rather than a video? Or does it only work with videos? My chief goal is to use this for FILM and then upscale the film video to 4K! I appreciate your time again!

**Comment by styler00dollar** [comment]
VapourSynth is mainly used for videos. While its technically possible to use images, this is not recommended and not that easy to do. Working with images is also slow. What dependencies you need depends on what you want to run. I did it more modular since I complaints that setup times are big. You need VapourSynth in any case, but the other stuff depends. For upscaling with engine files with CUGAN you would need TensorRT, vs and vs-mlrt for example. FILM depends on vs and tensorflow and tensorflow should be preinstalled on colab.

**Comment by AIManifest** [comment]
Ok thank you for your response. So please tell me, what code would I use to use FILM on this notebook and then which execution cell would I use to upscale the video created by FILM? My process would preferably be: original 960x540 video—>FILM Interpolation—> upscale FILM video. Please advise how to do this:)

**Comment by styler00dollar** [comment]
Like I said, "upscaling" is very vague since that also depends on what architecture, backend and method you use, and I gave instructions on what to do for FILM and CUGAN as an example. For FILM all you need is "initial setup", "download vs", "download models". Adjust `inference.py` accordingly.

**Comment by styler00dollar** [comment]
Was this help enough? If yes I would close this issue.
