### ISSUE TITLE
Add  "Video-Frame-Interpolation-Transformer"

### ISSUE THREAD

**Issue by Tsubajashi** [styler00dollar/VSGAN-tensorrt-docker#3]
Here is a link to their code and paper: https://github.com/zhshi0816/Video-Frame-Interpolation-Transformer
here is a video example: https://www.youtube.com/watch?v=DYkJYB7-NIg
sounds like interesting tech. You may want to add it in the future.

**Comment by styler00dollar** [comment]
If I remember correctly, I already tried to add it and the highest resolution I could get with that was around 256p due to out of memory errors. Maybe a little higher. Won't add since it's not usable for higher resolutions. I would like to have around 480p or more for interpolation, which sadly is not the case here.

**Comment by Tsubajashi** [comment]
completely understandable.
