### ISSUE TITLE
NCNN Needed Please : Suggestion : ChaiNNer 

### ISSUE THREAD

**Issue by tidypy** [styler00dollar/VSGAN-tensorrt-docker#39]
Hello Sir;  
Please convert .pth to .bin for NCNN Vulcan.  
If Not;  Please note you 'may' be able to convert with ChaiNNer, but at the effort of the layman. 
If Not; Please simply post this possibility in your Read.me; 
End If; suffice to say; Huggingface + Gradio, is also an option you have many models.

**Comment by styler00dollar** [comment]
I am not really sure what you mean, but if you want to convert `pth` to `bin/param` you can use `convert_compact_to_onnx.py` , `convert_esrgan_to_onnx.py` or any other `onnx` and then use [`convertmodel.com`](https://convertmodel.com/) to convert `onnx` to `bin/param`. (Sometimes it is harder and doesn't work out of the box, for example with rife.) 

Since ncnn is never really much faster than TensorRT and ncnn in docker only works in Linux, you should use TensorRT anyway. My docker is made for Nvidia GPUs after all due all the CUDA stuff.

**Comment by styler00dollar** [comment]
Closing due to no reply. I think it is solved.
