### ISSUE TITLE
Is there inefficiency in having multiple models chained?

### ISSUE THREAD

**Issue by darkcristle** [styler00dollar/VSGAN-tensorrt-docker#54]
First let me preface with "I am not really super familiar with the technical details", so if this is a dumb question my bad.

I currently have two models that I am running inference with.  A pre-processor and then the upscale model.   I have essentially copied and pasted the code for loading a trt model in inference_config.py.    Is the data being copied back to the CPU in between the models or is python/vspipe smart enough to leave the data in GPU memory?

Is there a proper/preferred wait to do this?    Google seemed to suggest merging the onnx models together but this seemed fairly complex.   Is there a more straightforward way that you support in your application?     If not, is it possible for you to add a better management system for this in the future?

Thanks.

**Comment by styler00dollar** [comment]
When you use `core.trt` the processing itself is done on GPU, but the output is stored in `RGBH`/`RGBS` cpu vapoursynth clips. These standartized vaporsynth formats make the chained usage of different plugins possible. There is no easy way to just reuse the allocated image between two instances of `core.trt` because vapoursynth does not support GPU clips which is used as an intermediate representation. Even if it would support such, it would require zero-copy support. Such functionality is in cupy for example. The only good way would be to make major adjustments to the plugin C++ code and give multiple paths as a parameter which I will don't want to do. An alternative way would be to do processing with the vapoursynth python api and only return a clip when you are done, but the python approach is probably slower in general.

The cleaner solution is to have one onnx file. You create one model class which contains both models, load the weights into each of them and export that class as one onnx. Then you can just use it like one model. May be even better because of trtexec optimizations as well. It isn't that hard once you get familiar with the python torch api.

```python
class your_model(nn.Module):
    def __init__(self):
        super(your_model, self).__init__()
        self.model1 = ...
        self.model1.load_state_dict(torch.load("model1.pth", map_location="cpu"), strict=True)
        self.model2 = ...
        self.model2.load_state_dict(torch.load("model2.pth", map_location="cpu"), strict=True)

    def forward(self, x):
        x = self.model1(x)
        x = self.model2(x)
        return x

model = your_model()
model.eval()

with torch.inference_mode():
    dynamic_axes = {
        "input": {0: "batch_size", 2: "width", 3: "height"},
        "output": {0: "batch_size", 2: "width", 3: "height"},
    }

    torch.onnx.export(
        model.cuda(),
        torch.rand(1, 3, 256, 256).cuda(),
        "model.onnx",
        verbose=False,
        opset_version=18,
        input_names=["input"],
        output_names=["output"],
        dynamic_axes=dynamic_axes,
    )
```

The copying of data isn't even really a major concern as long as your output speed is below a hundred fps which no upscaling model will archive in most usecases and you can decrease the data amount with `RGBH` by utilizing fp16 instead of fp32. What I can see happening is that more complex workflows with more filters can impact queuing and add delays, but the model processing will still take up a major part in the pipeline since upscaling is slow.

I will just close the issue due to the amount of work I would have for a not satisfying solution. Just export as one onnx, that would be the best approach.
