### ISSUE TITLE
Convert RIFE onnx to tensorrt fail.

### ISSUE THREAD

**Issue by jhl13** [styler00dollar/VSGAN-tensorrt-docker#55]
Using TensorRT 8.4.1.

[E] Error[4]: [shuffleNode.cpp::symbolicExecute::392] Error Code 4: Internal Error (/Reshape: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])

Do I have to use trt9.1? TensorRT 9.1 has not been officially released yet.

**Comment by styler00dollar** [comment]
`grid_sample` which rife uses got introduced with opset 16 and the onnx files are opset 18. Your TensorRT version is too old, since this operator got introduced in [TensorRT 8.5](https://github.com/NVIDIA/TensorRT/issues/2005). I would recommend to at least get 8.6 [since it supports `grid_sample`](https://docs.nvidia.com/deeplearning/tensorrt/operators/docs/GridSample.html) and works with opset 18. The latest officially public version is currently [9.2](https://github.com/NVIDIA/TensorRT/releases/tag/v9.2.0) which I use.

**Comment by jhl13** [comment]
> `grid_sample` which rife uses got introduced with opset 16 and the onnx files are opset 18. Your TensorRT version is too old, since this operator got introduced in [TensorRT 8.5](https://github.com/NVIDIA/TensorRT/issues/2005). I would recommend to at least get 8.6 [since it supports `grid_sample`](https://docs.nvidia.com/deeplearning/tensorrt/operators/docs/GridSample.html) and works with opset 18. The latest officially public version is currently [9.2](https://github.com/NVIDIA/TensorRT/releases/tag/v9.2.0) which I use.

Thanks!
