### ISSUE TITLE
Mpv is broken on all docker files.

### ISSUE THREAD

**Issue by ghost** [styler00dollar/VSGAN-tensorrt-docker#59]
it gives dependency issues for example
libcrypt-dev : depends: libcrypt1 (= 1:4.4.36-2) but 1:4.4.36-4 is installed
guess time to update its ubuntu or some?
Is there any specific line to put this on dockerfile? or does not it matter
```
RUN apt install mpv -y && apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install --yes pulseaudio-utils && \
  apt-get install -y pulseaudio && apt-get install pulseaudio libpulse-dev osspd -y && \
  apt-get autoclean -y && apt-get autoremove -y && apt-get clean -y 
  ```

**Comment by styler00dollar** [comment]
I removed mpv some time ago to keep the docker simpler and smaller since nobody used mpv. I didn't test it lately. It is easier to just render into mkv and watch that file in realtime than setting up ui and audio with docker. I may just remove that part of the readme if it doesn't work easily. My docker currently uses `nvidia/cuda:12.1.1-runtime-ubuntu22.04`. I can't update that since torch still uses cuda 12.1 and there is only up to 22.04 from nvidia. 

What I do as a workaround for dependency version issues, [I force install specific packages](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/0f3f0a9e262ed409e9891c17a669d7a2dd80d627/Dockerfile#L861) and you could adjust the [libcrypt deb](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/0f3f0a9e262ed409e9891c17a669d7a2dd80d627/Dockerfile#L770C1-L770C92) in that case. May be easier to just install mpv in the [base stage](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/0f3f0a9e262ed409e9891c17a669d7a2dd80d627/Dockerfile#L532) and copy over all needed files into the [final stage](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/0f3f0a9e262ed409e9891c17a669d7a2dd80d627/Dockerfile#L782) like I already did for other dependencies.

**Comment by ghost** [comment]
@styler00dollar thanks for quick reply. Can you give detailed explanation usage of this `It is easier to just render into mkv and watch that file in realtime than setting up ui and audio with docker` so people does not know about docker like me can understand

**Comment by styler00dollar** [comment]
I meant that you can use vspipe to render a file into mkv and then use your operating system video player to open that file while it is rendering. For example, you render with `vspipe -c y4m inference.py - | ffmpeg -i pipe: example.mkv -y` with docker and just open it with your own mpv and not with docker.

**Comment by ghost** [comment]
@styler00dollar okay the problem is setting path for files. I put mkv files on vsgan's directory but i get this
```
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 3225, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 3226, in vapoursynth._vpy_evaluate
  File "inference_batch.py", line 8, in <module>
    globals()["source"],
    ~~~~~~~~~^^^^^^^^^^
KeyError: 'source'

[in#0 @ 0x5820ebf57000] Error opening input: Invalid data found when processing input
Error opening input file pipe:.
Error opening input files: Invalid data found when processing input
```
