### ISSUE TITLE
Clarification questions (ffmpeg build, dropped openv)

### ISSUE THREAD

**Issue by abcnorio** [styler00dollar/VSGAN-tensorrt-docker#77]
Hello,

1- is there a reason that `ffmpeg` is build based on arch and not `ubuntu`/`debian` based?
2- compared to an older `Dockerfile` the `opencv` part is now dropped, what is the reason for it?

Thanks for clarifications!

**Comment by styler00dollar** [comment]
> 1- is there a reason that ffmpeg is build based on arch and not ubuntu/debian based?

I want to ensure that I build my ffmpeg as new as I reasonably can. I tried to be deb based, but I then had a too old `nasm` and couldn't compile it myself from scratch for example. Older versions may result in worse performance, so it was easier to get everything working with arch. I was thinking of trying to go away from arch, but that would mean to figure out how to compile certain things which also would increase docker build time or use outdated software.

> 2- compared to an older Dockerfile the opencv part is now dropped, what is the reason for it?

I wanted to remove OpenCV since a while now, but I had a color fix which used it as a depdendency.

https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/13f1210df76d33c120ceb04f67335b3eff760341/color_transfer.py#L4

This color script can be considered replaced with [pifroggi/vs_colorfix](https://github.com/pifroggi/vs_colorfix), which is better. I added it when I removed OpenCV.

The second reason is that OpenCV had an absurd amount of dependencies. I don't want to maintain this or have this bloat my final docker size.

https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/ac47012b9313fe76f37914601dafea82df0e94e6/Dockerfile#L840-L873
