### ISSUE TITLE
What's different about "cugan_pro-no-denoise3x-up3x"?

### ISSUE THREAD

**Issue by KirbyStar47** [styler00dollar/VSGAN-tensorrt-docker#83]
I noticed that the CUGAN Pro Up3x here has "no-denoise" and "no-denoise3x". 

What is the difference between these two models? I thought the original CUGAN Pro only have 3 denoise levels.

Comparing hashes, the two files seem to be the same thing.

**Comment by styler00dollar** [comment]
I just downloaded the models [from the official github](https://github.com/bilibili/ailab/releases/download/Real-CUGAN/updated_weights.zip) and there is no such thing as `no-denoise3x`. The files seem identical and I didn't notice that. I deleted the 3x one since applying no noise 3 times makes no sense. Probably did a mistake while exporting onnx.
