### ISSUE TITLE
docker apt install couldn't fix

### ISSUE THREAD

**Issue by ppeterpp** [styler00dollar/VSGAN-tensorrt-docker#84]
hi, i pulled your released image, and docker run it, where inside the docker `apt install` reveals several errors
for example with `apt-get install vim`:

The following packages have unmet dependencies:
 libc6 : Breaks: base-files (< 13.3ubuntu1~) but 12ubuntu4.6 is to be installed
         Breaks: systemd (< 256~rc4-1~) but 249.11-0ubuntu3.12 is to be installed
 libnsl-dev : Depends: libnsl2 (= 1.3.0-3build3) but 1.3.0-2build2 is to be installed
 libtirpc3t64 : Depends: libtirpc-common (>= 1.3.4+ds-1.3) but 1.3.2-2ubuntu0.1 is to be installed
                Breaks: libtirpc3 (< 1.3.4+ds-1.3)
 vim : Depends: vim-common (= 2:8.2.3995-1ubuntu2.21) but 2:8.2.3995-1ubuntu2.17 is to be installed
       Depends: vim-runtime (= 2:8.2.3995-1ubuntu2.21) but 2:8.2.3995-1ubuntu2.17 is to be installed

is there anything i can do to fix `apt install`?

**Comment by ppeterpp** [comment]
Is it able to enable ssh on any of your released dockers? Please shed some light!

**Comment by styler00dollar** [comment]
This is required to have my custom arch ffmpeg working. Arch is usually too new and can throw glibc errors otherwise if I copy the arch binary onto another docker base image. I manually install new package versions to fix my ffmpeg and that breaks apt.

If you really need custom packages, you can add `apt install vim -y` before doing `dpkg --force-all -i *.deb`. After that command apt stops working.

https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/2543035440c9cddfdff749dab2d4180b0e0d5963/Dockerfile#L880

I don't know how to get apt working with my current ffmpeg and I don't see it as important. `ffmpeg` and `vspipe` work and software should be added directly into the `Dockerfile` instead of using apt, because changes in an active docker are temporary.
