### ISSUE TITLE
model conversion from onnx to trt

### ISSUE THREAD

**Issue by deism** [styler00dollar/VSGAN-tensorrt-docker#9]
@styler00dollar  this is not issue but a question, I read the scripts in inference.py and found real-esrgan 2x is loaded from trt engine file, since real-2x uses dynamic shapes as input, could you share any ideas how to convert this model to trt, thanks!

**Comment by styler00dollar** [comment]
RealESRGAN 2x is a custom model I currently train and it is not public yet. I added it to benchmarks out of data curiosity. The official 2x models do not work with TensorRT, because it does not support pixel unshuffle. 2x and 4x differ in implementation in the current official repository. I have some slightly different implementation in my custom model (using old esrgan arch instead) to make it compatible again. I hope that answers your question. If yes then I can close the issue.  You can use the official 4x models instead If you want to use the RealESRGAN models.

**Comment by deism** [comment]
Thanks!

**Comment by styler00dollar** [comment]
I was approached by tepete and he seemingly found a workaround to get `RealESRGAN_x2plus` working.
![image](https://user-images.githubusercontent.com/51405565/174452894-c81eb364-91a4-4f5d-985d-48fc99ae5eeb.png)
I did not test it myself, but this might help.
